      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential automake autoconf libtool pkg-config libssl-dev
          
      - name: Clone cpuminer-opt
        run: git clone https://github.com/JayDDee/cpuminer-opt.git

      - name: Build cpuminer-opt
        run: |
          cd cpuminer-opt
          ./build.sh
